### PR TITLE
Update mock-res to version ^0.4.1

### LINKED ISSUE #5: Does not support response.finished
See https://nodejs.org/api/http.html#http_response_finished

### PR DESCRIPTION
**Pull request by nikwen**
Fixes #5 

See https://github.com/diachedelic/mock-res/pull/9

### CODE REVIEW

**Comment by nikwen** [comment]
Updated the PR to explicitly include https://github.com/diachedelic/mock-res/pull/10 as it fixes a major bug in the implementation of res.finished.

**Comment by nikwen** [comment]
@lykmapipo What about this PR? Can you merge it, please? Thanks! :)

**Comment by nikwen** [comment]
Thanks a lot for merging. :)

Could you please also do an npm release containing the changes?

**Comment by lykmapipo** [comment]
@nikwen done

**Comment by nikwen** [comment]
Thanks a lot! :)

**Pull request merged**
